-- YouCompleMe
-- Info de instalación en: https://github.com/ycm-core/YouCompleteMe#installation
-- 1. PlugInstall y cancelar con ctrl+C
-- 2. Salir de neovim e ir a ~/.local/share/nvim/plugged/YouCompleteMe
-- 3. Volver a descargar el repo: git submodule update --init --recursive
-- 4. Compilar e instalar: python3 install.py --clang-completer --ts-completer --cs-completer
-- 4. Alt:                 python3 install.py --all
-- 5. PlugInstall
-- Set to 1 YCM will autoclose the preview window
--vim.g.ycm_autoclose_preview_window_after_insertion = 1 -- único activado
--
--vim.g.ycm_complete_in_comments = 1 
--vim.g.ycm_seed_identifiers_with_syntax = 1 
--vim.g.ycm_collect_identifiers_from_comments_and_strings = 1 

-- YCM compatibilidad con UltiSnips.
--let g:ycm_use_ultisnips_completer = 1
--let g:ycm_key_list_stop_completion = ['<C-y>']
