--- Treesitter full `ensure_installed` list
return {
  "nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "css",
      "comment",
      "diff",
      "gitcommit",
      "html",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "toml",
      "sql",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
